FROM alpine:latest

RUN apk add --no-cache git busybox-extras

RUN git clone https://github.com/rudm4n/Stremio2Nuvio.git /tmp/app &&     mkdir -p /var/www &&     cp /tmp/app/index.html /var/www/index.html &&     rm -rf /tmp/app

EXPOSE 7860

CMD ["httpd", "-f", "-p", "7860", "-h", "/var/www"]
